### ISSUE TITLE
How to get IP connecting to server.

### ISSUE THREAD

**Issue by Nelie-Taylor** [PondWader/node-socks5-server#1]
Hi, thank you for your opensource.
I want get IP connecting by server.setAuthHandler to make auth by IP.
I cannot find any variable IP connect.
Please help me get IP client in server.setAuthHandler.
Thank you.

**Comment by Nelie-Taylor** [comment]
I just create PR for parse IP when connect.
https://github.com/PondWader/node-socks5-server/pull/2
Please check help me.
Thank you.

**Comment by PondWader** [comment]
You can do this by accessing the .socket property on a Socks5Connection instance.

It's worth noting that setAuthHandler will require a username and password to be provided since username-password login status is a separate part of the socks5 specification. 

If you don't want username-password authentication you can do IP authentication using a ruleset validator like so:
```ts
import { createServer } from "@pondwader/socks5-server";
import net from "net";

const ALLOWED_IPS = new Set([
    '10.0.0.0',
    '127.0.0.1'
]);

createServer()
    .listen(1080, () => console.log('Socks5 server listening on port 1080'))
    .setRulesetValidator(conn => {
        const remoteAddress = (conn.socket as net.Socket).remoteAddress
        return remoteAddress !== undefined && ALLOWED_IPS.has(remoteAddress.replace(/^.*:/, ''));
    });
```
If you also want username password authentication you can use setAuthValidator with the IP check inside it.
